type Quarterly = {
  acceptedDate: Date | null;
  calendarYear: string;
  cik: string;
  costAndExpenses: number;
  costOfRevenue: number;
  date: Date;
  depreciationAndAmortization: number | null;
  ebitda: number;
  ebitdaratio: number;
  eps: number;
  epsdiluted: number;
  fillingDate: Date | null;
  finalLink: string | null;
  generalAndAdministrativeExpenses: number;
  grossProfit: number;
  grossProfitRatio: number;
  id: number;
  incomeBeforeTax: number;
  incomeBeforeTaxRatio: number;
  incomeTaxExpense: number;
  interestExpense: number;
  interestIncome: number;
  link: string | null;
  netIncome: number;
  netIncomeRatio: number;
  operatingExpenses: number;
  operatingIncome: number | null;
  operatingIncomeRatio: number;
  otherExpenses: number;
  period: string;
  reportedCurrency: string;
  researchAndDevelopmentExpenses: number;
  revenue: number;
  sellingAndMarketingExpenses: number;
  sellingGeneralAndAdministrativeExpenses: number;
  totalOtherIncomeExpensesNet: number;
  weightedAverageShsOut: number;
  weightedAverageShsOutDil: number;
};
