import type { NextPage } from "next";
import Head from "next/head";
import Script from "next/script";

const Home: NextPage = () => {
  return (
    <>
      <Script
        id="gtag-1"
        strategy="lazyOnload"
        src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS}`}
      />
      <Script id="gtag-2" strategy="lazyOnload">
        {`
           window.dataLayer = window.dataLayer || [];
           function gtag(){dataLayer.push(arguments);}
           gtag('js', new Date());
           gtag('config', '${process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS}', {
           page_path: window.location.pathname,
           });
       `}
      </Script>

      <Head>
        <title>Playing around with stock APIs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className="flex flex-col items-center justify-center gap-6 bg-gradient-to-b from-fuchsia-700"
        style={{ minHeight: "100vh" }}
      >
        <h1 className="text-white text-6xl">
          Playing around with some stock APIs
        </h1>
        <h4 className="text-white text-2xl">
          Might build some SVG graphs and some sorting for a variety of tickers.
        </h4>
        <button>View Stock List Here</button>
      </main>

      <footer></footer>
    </>
  );
};

export default Home;
